---
- name: Detalhes do sistema
  ansible.builtin.debug:
    msg:
    - "Distro: {{ ansible_distribution }}"
    - "Codinome: {{ ansible_distribution_release }}"
    - "Versão: {{ ansible_distribution_version }}"

- name: Instalação de pacotes base do sistema
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: Instalação do cockpit e do plugin de métricas do cockpit
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - cockpit
    - cockpit-pcp

- name: Habilitação do socket do cockpit
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - cockpit.socket
    - pmlogger.service

- name: Criação de usuário para acesso ao cockpit
  ansible.builtin.user:
    name: mastodoncio
    password: "{{ 'semsenha' | password_hash('sha512', 'saltbemcomplexo') }}"
    groups: sudo
    append: true
    state: present
    createhome: true
    shell: /bin/bash
    update_password: on_create
  register: reg_usuario