version: '3'
name: nginx
services:
  nginx:
    image: "docker.io/library/nginx:latest"
    container_name: nginx
    restart: always
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - nginx_log:/var/log/nginx
      - nginx_vhost:/etc/nginx/vhosts
      - nginx_certs:/etc/nginx/certs
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]
      timeout: 10s

volumes:
  nginx_log:
    driver_opts:
      type: none
      device: /opt/nginx/logs
      o: bind
  nginx_vhost:
    driver_opts:
      type: none
      device: /opt/nginx/conf/vhost
      o: bind
  nginx_certs:
    driver_opts:
      type: none
      device: /opt/nginx/conf/certs
      o: bind